### ISSUE TITLE
Model-rng only for Regressor

### ISSUE THREAD

**Issue by talpay** [lmjohns3/theanets#112]
The new model-wide rng parameter is only propagated to graph.Network when using recurrent.Regressor and feedforward.Regressor. Classifiers and Autoencoders do not pass the parameter in their super-calls. At least it seems like it to me because both models give this error:

net = theanets.Autoencoder([784, args.features ** 2, 784], rng=42)
TypeError: __init__() got an unexpected keyword argument 'rng'

**Comment by lmjohns3** [comment]
Thanks for the report! Just released v0.7.2 with a fix.
