### ISSUE TITLE
'SGD' object has no attribute 'iterate'

### ISSUE THREAD

**Issue by pannous** [lmjohns3/theanets#113]
Looks like theanets==0.8.0rc0 is losing backwards compatibility:

theanets/trainer.py", line 65, in itertrain
    monitor_gradients=kwargs.get('monitor_gradients', False),
AttributeError: 'SGD' object has no attribute 'iterate'

  File "build/bdist.macosx-10.10-x86_64/egg/theanets/graph.py", line 333, in create_dataset
TypeError: __init__() got an unexpected keyword argument 'rng'

**Comment by lmjohns3** [comment]
I'm confused, it looks like there are two different tracebacks here. Could you include more of the code that produces these errors?

Also can you include the output of:

```
>>> import theanets, downhill
>>> print(theanets.__version__, downhill.__version__)
```

**Comment by pannous** [comment]
Thanks for the hint, reinstalling downhill helped somehow!
