### ISSUE TITLE
[DOCS] Update MNIST example to use 2D Convolutions

### ISSUE THREAD

**Issue by 4science** [lmjohns3/theanets#115]
Hello again,

I really enjoyed the MNIST example you provided it was clear and simple to reproduce, however now that 2D convolutions are available I would suggest updating the example where the input is the 28x28 image instead of 784x1.

Hope this helps, also is there an available example of how to use the 2D convolutions? Issue #80 has been closed and it said there would be one, otherwise I just can't find it. :(

**Comment by lmjohns3** [comment]
I added a quick example. There's more work to be done in this area, particularly in the pooling layers and documentation. But thanks for filing these issues!
