### ISSUE TITLE
After finishing training, get the number of iterations 

### ISSUE THREAD

**Issue by sadatanwer** [lmjohns3/theanets#122]
I am using the lib for my masters thesis, and for evaluation, my supervisor thought it would be nice to get the number of iterations the training took, for now, I have edited the code in net.itertrain to yield the i and then return it from net.train it works, but I wanted to know if there is a proper way of doing it? 
Thanks

**Comment by lmjohns3** [comment]
Editing the itertrain isn't too bad ... but you could also run your own training loop:

    for i, (tm, vm) in enumerate(net.itertrain(...)):
        pass

This is probably what you're already doing, but you can do it in your own code instead of inside ``theanets``.
