### ISSUE TITLE
Number of Iterations

### ISSUE THREAD

**Issue by kadarakos** [lmjohns3/theanets#17]
Can set the number of iterations? or number of maximum iterations/epochs?

**Comment by fedorajzf** [comment]
where to set num_updates ?

**Comment by lmjohns3** [comment]
This ``--num-updates`` solution is quite old at this point.

To set the number of iterations to N, you'll need to do some acrobatics with the early stopping criteria:

    patience=0,
    validate_every=N,
    min_improvement=0.999,

This will ensure that the first validation attempt will fail, and the first failed validation attempt will exhaust the patience of the early stopping mechanism.

You can read more about early stopping at http://downhill.readthedocs.org/en/stable/guide.html#patience-and-improvement
