### ISSUE TITLE
Distributed Computing Feature Request

### ISSUE THREAD

**Issue by kadarakos** [lmjohns3/theanets#20]
The theanets package is working perfectly for me so far its very easy to use and have enough features to solve my problem, so basically Good Job! 
My only issue is that I cannot use my available architecture to its fullest as I have access to a server of 26 cores and as far as I understand theanets does not have the ability to train a model on a cluster. I think it would make theanets more versatile and also way faster. If theanets would do cluster computing it would be my dream neural network package :-).

Cheers

**Comment by nkundiushuti** [comment]
I have access to an hpc cluster here but no gpu. It would be great to have something implemented for parallelization. I know that Theano is doing some effort regarding this.

**Comment by lmjohns3** [comment]
With a heavy heart I'm going to close this since it's just going to be too broad for me to address by myself. If anyone wants to reopen, please create a new issue at lmjohns3/downhill, since that's where the actual optimization stuff happens.
