### ISSUE TITLE
supervised layerwise pre-training details

### ISSUE THREAD

**Issue by AminSuzani** [lmjohns3/theanets#28]
Hi, 

First of all, thanks for this super useful library. I need to learn about (and also cite) the "layerwise pre-training" (when we set optimize='layerwise'). I have two basic questions:

1- Assume we have a network with 4 hidden layers: [100, 200, 300, 200, 50, 20].  At first step, the network [100,200,20] is trained. At second step, does it train a [100,200,300,20]  network (simply adding next layer and train) or a [200,300,20] network (using the pre-trained first hidden layer as input layer)?

2- Do you know any paper or tutorial that explains this approach? I searched and also looked through Bengio's works. I found several papers for unsupervised layerwise pre-training. However, here it seems that we are doing supervised pre-training (because output layer is always used in our pre-training steps). Am I wrong about this?

Thanks,
Amin

**Comment by andi1400** [comment]
Hi, 
first of all thanks for this great library which I am using a lot for master thesis project!

I'd like to cite your work, the library in general and especially the supervised pretrainer as described above. Do you have any preferred way of citing this, any paper or whatever?

Thanks,
Andi

**Comment by lmjohns3** [comment]
I don't have a paper written about theanets; I ought to fix that now that my dissertation is finished. For the time being just include a link to the source: https://github.com/lmjohns3/theanets. (I'm happy you're finding the library useful!)

For the supervised pretraining citation, look at Bengio, Lamblin, Popovici & Larochelle (NIPS 2006) "Greedy Layer-Wise Training of Deep Networks" http://papers.nips.cc/paper/3048-greedy-layer-wise-training-of-deep-networks.pdf -- the method used in the layerwise pretrainer is the "TrainGreedySupervisedDeepNet" algorithm, described in the appendix.
