### ISSUE TITLE
Unsupervised Pretraining Feature Request

### ISSUE THREAD

**Issue by bmilde** [lmjohns3/theanets#39]
Yes, I know, there is this growing sentiment that unsupervised pretraining (e.g. with Restricted Boltzman Machines) is becoming obsolete in neural nets by the recent advancements in regularisation and better optimisations techniques for back-propagation. I beg to differ though. Unsupervised pretraining would allow the use of a much bigger set of unlabeled data first, while fine-tuning is done on a much smaller labeled data set. In other words, it could be helpful beyond just finding a better initialisation for the weights.

It would be lovely if we could do something similar to this in theano-nets:

exp = theanets.Experiment(theanets.Classifier)

exp.add_dataset('pretrain', unlabeled_dataset)
exp.add_dataset('train', labeled_dataset[:1000])
exp.add_dataset('valid', labeled_dataset[1000:])
exp.train()

That way, the (potentially unlabeled) pretrain data set can be different from the labeled training set, e.g. be much bigger.

**Comment by lmjohns3** [comment]
I just added a "deep classifier" example. I'm going to go ahead and close this.
