### ISSUE TITLE
batch_size=1 does not work

### ISSUE THREAD

**Issue by majidaldo** [lmjohns3/theanets#40]
e = theanets.Experiment(
        theanets.recurrent.Regressor
        #theanets.recurrent.Autoencoder
        ,layers=(1, 10, 1)
        ,batch_size=1
        )

gives

    TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable Subtensor{::
    -1}.0) into Type TensorType(float32, (False, True, False)). You can try to manua
    lly convert Subtensor{::-1}.0 into a TensorType(float32, (False, True, False)).

**Comment by lmjohns3** [comment]
I'm going to close this since it's not an issue with theanets; we'll need to wait until theano has a fix for this issue with the scan() function.
