### ISSUE TITLE
Large dataset numpy arrays solution - store batches on hard drive?

### ISSUE THREAD

**Issue by nkundiushuti** [lmjohns3/theanets#59]
I have tried to load big matrices into numpy arrays and then to call the dataset creation routines. However, very large data can pose memory issues for numpy. Usually we need lots of data for deep learning and this data cannot be kept all in memory. 
It would be nice to have the batches stored on hard drive in different parts, and loading these parts into memory at training one by one, rather than the full dataset. Maybe I can try to implement something like this. In this case should the train function should be modified or what is the best way?

**Comment by lmjohns3** [comment]
Have you tried using a callable for your datasets? Maybe something like this, which chooses a random dataset and a random offset for each batch:

  SOURCES = 'foo.npy', 'bar.npy', 'baz.npy'
  BATCH_SIZE = 64
  def batch():
      X = np.load(np.random.choice(SOURCES), mmap_mode='r')
      i = np.random.randint(len(X))
      return X[i:i+BATCH_SIZE]
  exp.train(batch)

You can do anything inside this callable, including loading up arrays from disk, as long as it takes no arguments and returns a numpy array with the correct shape.

**Comment by lmjohns3** [comment]
If you need more sophistication from your callables, you can also encapsulate them inside a class, just make sure instances of the class are callable by defining the ``__call__`` method:

    class LargeDataset:
        def __init__(sources=('foo.npy', 'bar.npy', 'baz.npy'), batch_size=64):
            self.sources = sources
            self.batch_size = batch_size
            self.src = -1
            self.idx = 0
            self.X = ()

        def __call__(self):
            if self.idx + self.batch_size > len(self.X):
                self.idx = 0
                self.src = (self.src + 1) % len(self.sources)
                self.X = np.load(self.sources[self.src], mmap_mode='r')
            try:
                return self.X[self.idx:self.idx+self.batch_size]
            finally:
                self.idx += self.batch_size

I haven't tested this but it should be close.

**Comment by nkundiushuti** [comment]
thanks! I haven't tried with callables at all until now. I was using the dataset class for some arrays. I will give it a try!

**Comment by majidaldo** [comment]
have you tried `http://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html#numpy.memmap`? but i'm pretty sure that writing your own callable would be more efficient.

**Comment by lmjohns3** [comment]
+1 -- memmap is pretty great. It can run into issues with multiple processes, but mostly it's a good idea.

**Comment by varghesealex90** [comment]
I would like to train the network with all possible arrays(foo,baz,bar) ,with the following constrains
1. Only one dataset is loaded at a time (to save RAM /memory related issues) 
i
2. The weights learnt after loading foo.npy and training on 'foo.npy' is the starting point when 'baz.npy' is called upon .

###########################################
exp=theanets.Experiment(theanets.Autoencoder,layers=(x,x/2,x/4,x),tied_weights=True)
Sources='foo.npy', 'bar.npy', 'baz.npy'
for i in range(len(Sources)):
     training_batch=np.load(Sources[i],mmap_mode='r')
     exp.train(training_batch)
########################################

**Comment by lmjohns3** [comment]
Yes, that looks fine.
