### ISSUE TITLE
Calling a parent script with args which embeds theanets Experiment from command line triggers an error in theanets

### ISSUE THREAD

**Issue by nkundiushuti** [lmjohns3/theanets#60]
There is a script which is launched from command line with an arg which specifies the input directory for the features files. So I call the script like this 
python lstm_ex.py --input_path /path/to/input/dir
I receive an error, which is triggered when the experiment is initialized
usage: lstm_ex.py [-h] [--help-activation] [--help-optimize]
                      [-n N [N ...]] [-g FUNC] [--output-activation FUNC] [-t]
                      [--decode N] [-O ALGO [ALGO ...]] [--no-learn-biases]
                      [--num-updates N] [-p N] [-v N] [-b N] [-B N] [-V N]
                      [--save-progress FILE] [--save-every N]
                      [--contractive-l2 S] [--input-noise S]
                      [--input-dropouts R] [--hidden-noise S]
                      [--hidden-dropouts R] [--hidden-l1 K] [--hidden-l2 K]
                      [--weight-l1 K] [--weight-l2 K] [-l V] [-m V]
                      [--min-improvement R] [--gradient-clip V]
                      [--max-gradient-norm V] [--rms-halflife N]
                      [--rprop-increase R] [--rprop-decrease R]
                      [--rprop-min-step V] [--rprop-max-step V] [-C N]
                      [--initial-lambda K] [--global-backtracking]
                      [--preconditioner] [--recurrent-error-start T]
lstm_ex.py: error: unrecognized arguments: --input_path 
I think something gets mixed up during climate processing of input args...

**Comment by lmjohns3** [comment]
Hm, yes, I've seen this before with IPython arguments ... I think it might require a change to climate. I'll have a look in the next couple days.

In the meantime, if you have control over the ``lstm_ex.py`` script, then you can declare the argument using climate (instead of, say, argparse or optparse), and climate will then know about it:

    climate.add_arg('--input_path', ...)

**Comment by nkundiushuti** [comment]
yes! you are right...it just needed to be added to climate but it can be processed with anything.
