### ISSUE TITLE
theanets.recurrent.Predictor throws an error 'TypeError: Tried to provide value for implicit input: rnn1_xh'

### ISSUE THREAD

**Issue by john-a-m** [lmjohns3/theanets#69]
Here's a copy and paste example of the code that is giving me the error

	#!/usr/bin/env python

	import climate
	import numpy as np
	import theanets

	import warnings
	warnings.filterwarnings("ignore")

	BS = 2

	climate.enable_default_logging()

	data = np.random.random((1000, BS, 7)), np.random.random((1000, 1))

	e = theanets.Experiment(
		theanets.recurrent.Predictor,
		layers=(7, ('rnn', 20), 1),
		batch_size=BS)

	for monitor in e.itertrain(data):
		print monitor[0].get('loss')

and here is the stacktrace I get

	Traceback (most recent call last):
	  File ".\test.py", line 21, in <module>
		for monitor in e.itertrain(data):
	  File "C:\Users\John\.virtualenvs\firstco\lib\site-packages\theanets\main.py", line 328, in itertrain
		for i, monitors in enumerate(opt.itertrain(**sets)):
	  File "C:\Users\John\.virtualenvs\firstco\lib\site-packages\theanets\trainer.py", line 248, in itertrain
		validation = self.evaluate(valid_set)
	  File "C:\Users\John\.virtualenvs\firstco\lib\site-packages\theanets\trainer.py", line 186, in evaluate
		values = [self.f_eval(*x) for x in dataset]
	  File "C:\Users\John\.virtualenvs\firstco\lib\site-packages\theano-0.6.0-py2.7.egg\theano\compile\function_module.py",
	line 590, in __call__
		self.inv_finder[c]))
	TypeError: Tried to provide value for implicit input: rnn1_xh

**Comment by john-a-m** [comment]
Never mind, my layers/data weren't properly setup

	#!/usr/bin/env python

	import climate
	import numpy as np
	import theanets

	import warnings
	warnings.filterwarnings("ignore")

	BS = 1

	climate.enable_default_logging()

	train = np.random.random((10, 20, 7))
	valid = np.random.random((10, 20, 7))

	e = theanets.Experiment(
		theanets.recurrent.Predictor,
		layers=(7, ('rnn', 20), 7),
		batch_size=BS)

	for monitor in e.itertrain(train, valid):
		print monitor[0].get('loss')

**Comment by lmjohns3** [comment]
Yeah, the predictor needs the same output dimension as input dimension.
