### ISSUE TITLE
Add convolution layers

### ISSUE THREAD

**Issue by lmjohns3** [lmjohns3/theanets#80]
It would be nice to have 2D and 3D convolutions in theanets!

This should be fairly straightforward, but will entail a bit of work:

- add Conv2 and Conv3 layers
- add a layer for reshaping inputs
- write documentation
- write tests
- add an example

**Comment by 4science** [comment]
"Bump"
Came here to add this feature request but looks like you've got it covered. Any status update?
Thanks @lmjohns3 for this great library.

**Comment by lmjohns3** [comment]
Commit b6416435 mostly takes care of this. I haven't written any larger-scale tests for it yet, however! Feel free to report issues that you find (including poor docs).
