### ISSUE TITLE
Problems continuing to train Experiment loaded from file.

### ISSUE THREAD

**Issue by atnelson** [lmjohns3/theanets#85]
I'm running 0.6.0rc0 and training a recurrent model with LSTM layers.

I would like to load a trained network from file and continue training on additional data. However, when I try this, I get:

  File "/Volumes/Archive/ExternalCode/theanets/theanets/main.py", line 193, in itertrain
    for i, monitors in enumerate(algo.itertrain(train, valid, **kwargs)):
  File "/Volumes/Archive/ExternalCode/theanets/theanets/trainer.py", line 65, in itertrain
    params=self.network.params,
  File "/Volumes/Archive/ExternalCode/theanets/theanets/graph.py", line 316, in params
    return [p for l in self.layers for p in l.params]
  File "/Volumes/Archive/ExternalCode/theanets/theanets/layers/base.py", line 204, in params
    return self._params + self.activate.params
AttributeError: 'function' object has no attribute 'params'

Inspecting the Experiment.network object, it appears that the params and num_params attributes are corrupted. 

Thanks,
Alex

**Comment by lmjohns3** [comment]
I can see where this went wrong; the activation function probably got serialized without the additional .name and .params attributes (which are basically empty for normal activation functions).

I've updated the code (see 325e43a) in master; if you're using the git master, could you check this out and give it a try?

**Comment by atnelson** [comment]
Okay, continued training seems to work now, thanks! This seems to be a fix in 0.7.0; I guess I'll move to the new (batch-first) indexing now, unless you plan to make this fix available in 0.6.2.

**Comment by lmjohns3** [comment]
Great!

I just merged this into the v0.6 branch and released v0.6.2.
