### ISSUE TITLE
feature: use file-like objects for net saving and loading

### ISSUE THREAD

**Issue by majidaldo** [lmjohns3/theanets#99]
i think it's worthwhile to use file-like objects to save networks. i'm systemizing my use of theanets and i'm going through temporary files to save networks in a db.

basically it allows for more flexibility and it's more pythonic. heck it wouldn't be too big of a deal to have users provide their file objects instead of specifying a filename to save() and load().

i'd do a PR but i'm not sure about future use of pickling in the code.

**Comment by lmjohns3** [comment]
This is a good idea! I'll try to get to it in the next couple of weeks.

**Comment by majidaldo** [comment]
goes for save_progress as well.

**Comment by lmjohns3** [comment]
For ``save_progress`` if I passed a file-like object, would the same object be overwritten each time the model was saved? Using ``seek(0)``?

**Comment by majidaldo** [comment]
@lmjohns3 good question! but this 'problem' would be left to be addressed by the user. you don't know the correspondence from obj -> file.

**Comment by lmjohns3** [comment]
I think this should do it, please reopen if not.
